#!/usr/bin/env node
/**
 * Generate conformance test vectors for draft-chapman-a2a-mls.
 *
 * Deliberately implements canonicalisation, did:key derivation and signing from the
 * SPECIFICATION TEXT rather than importing @qwixl/protocol. If the vectors were
 * generated by the implementation they would encode its bugs as the standard, and
 * conformance would be circular. Generating them independently means the vectors can
 * disagree with the implementation — which is the entire point of having them.
 *
 * Deterministic: fixed key seeds and fixed timestamps, so output is byte-stable and
 * a diff in the committed vectors always means a real semantic change.
 */
import { createPrivateKey, createPublicKey, sign as edSign } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT_DIR = dirname(fileURLToPath(import.meta.url));

/* ------------------------------------------------------------------ keys --- */

/** PKCS#8 DER prefix for a raw Ed25519 private seed (RFC 8410). */
const PKCS8_ED25519_PREFIX = Buffer.from("302e020100300506032b657004220420", "hex");

function keyPairFromSeed(seedHex) {
  const der = Buffer.concat([PKCS8_ED25519_PREFIX, Buffer.from(seedHex, "hex")]);
  const privateKey = createPrivateKey({ key: der, format: "der", type: "pkcs8" });
  const spki = createPublicKey(privateKey).export({ format: "der", type: "spki" });
  return { privateKey, publicKey: Buffer.from(spki.subarray(spki.length - 32)) };
}

const BASE58_ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

function base58btcEncode(bytes) {
  const digits = [0];
  for (const byte of bytes) {
    let carry = byte;
    for (let i = 0; i < digits.length; i++) {
      carry += digits[i] << 8;
      digits[i] = carry % 58;
      carry = (carry / 58) | 0;
    }
    while (carry > 0) {
      digits.push(carry % 58);
      carry = (carry / 58) | 0;
    }
  }
  let leadingZeros = 0;
  while (leadingZeros < bytes.length && bytes[leadingZeros] === 0) leadingZeros += 1;
  return (
    "1".repeat(leadingZeros) +
    digits
      .reverse()
      .map((d) => BASE58_ALPHABET[d])
      .join("")
      .replace(/^1+/, (m) => (leadingZeros > 0 ? "" : m))
  );
}

/** did:key = "did:key:z" + base58btc(0xed 0x01 || publicKey). */
function didKeyFromPublicKey(publicKey) {
  const multicodec = Buffer.concat([Buffer.from([0xed, 0x01]), publicKey]);
  return `did:key:z${base58btcEncode(multicodec)}`;
}

/* --------------------------------------------------- canonical form + sign --- */

/**
 * Canonical serialisation per the draft: object members sorted lexicographically by
 * UTF-16 code unit (JavaScript's default sort), undefined members omitted, array
 * order preserved, no insignificant whitespace.
 */
function canonicalise(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalise).join(",")}]`;
  const keys = Object.keys(value)
    .filter((key) => value[key] !== undefined)
    .sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalise(value[key])}`).join(",")}}`;
}

/** Only these seven members are covered by the signature. */
function signingPayload(object) {
  return canonicalise({
    version: object.version,
    id: object.id,
    issuerDid: object.issuerDid,
    issuedAt: object.issuedAt,
    semantic: object.semantic,
    payload: object.payload,
    governance: object.governance,
  });
}

function sign(unsigned, privateKey) {
  const canonicalForm = signingPayload(unsigned);
  const signature = edSign(null, Buffer.from(canonicalForm, "utf8"), privateKey);
  return {
    object: { ...unsigned, signatureAlgorithm: "ed25519", signature: signature.toString("base64") },
    canonicalForm,
  };
}

/* ----------------------------------------------------------------- fixtures --- */

const ALICE = keyPairFromSeed("00".repeat(31) + "01");
const BOB = keyPairFromSeed("00".repeat(31) + "02");
const ALICE_DID = didKeyFromPublicKey(ALICE.publicKey);
const BOB_DID = didKeyFromPublicKey(BOB.publicKey);

/** All time-dependent vectors are evaluated at this instant. */
const NOW = "2026-01-15T12:00:00.000Z";

function base(overrides = {}) {
  return {
    version: 1,
    id: "01948f00-0000-7000-8000-000000000001",
    issuerDid: ALICE_DID,
    issuedAt: "2026-01-15T11:59:00.000Z",
    semantic: { schema: "https://atom.qwixl.dev/schema/CommsMessage" },
    payload: { text: "hello" },
    governance: { purpose: "comms:message", ttlSeconds: 3600 },
    ...overrides,
  };
}

const vectors = [];

function addObjectVector({ id, description, requires, expect, reason, permittedPurposes, unsigned, key = ALICE.privateKey, mutate }) {
  const signed = sign(unsigned, key);
  let object = signed.object;
  if (mutate) object = mutate(structuredClone(object));
  vectors.push({
    id,
    kind: "data-object",
    description,
    requires,
    now: NOW,
    ...(permittedPurposes ? { permittedPurposes } : {}),
    expect,
    ...(reason ? { reason } : {}),
    ...(mutate ? {} : { canonicalForm: signed.canonicalForm }),
    object,
  });
}

const DEFAULT_PERMITTED = ["comms:message", "comms:receipt", "coordination:proposal"];

/* --- accept --- */

addObjectVector({
  id: "001-valid-comms-message",
  description: "Minimal well-formed object signed by its stated issuer.",
  requires: ["governed-object", "processing"],
  expect: "accept",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base(),
});

addObjectVector({
  id: "002-canonicalisation-nested-unicode",
  description:
    "Exercises canonicalisation: members deliberately authored out of order, nested objects, arrays whose order must be preserved, non-ASCII keys and values, and an empty object. An implementation that sorts incorrectly, reorders arrays, or mishandles UTF-16 ordering will produce a different canonical form and fail signature verification.",
  requires: ["canonical"],
  expect: "accept",
  permittedPurposes: ["coordination:proposal"],
  unsigned: {
    version: 1,
    id: "01948f00-0000-7000-8000-000000000002",
    issuerDid: ALICE_DID,
    issuedAt: "2026-01-15T11:59:00.000Z",
    semantic: {
      version: "1.2",
      schema: "https://atom.qwixl.dev/schema/SchedulingProposal",
    },
    payload: {
      zulu: "last key alphabetically",
      Alpha: "uppercase sorts before lowercase in UTF-16",
      "café": "non-ASCII key",
      "\u00e9clair": "combining vs precomposed matters",
      nested: { b: 2, a: 1, c: { deep: [3, 1, 2] } },
      slots: ["2026-02-01T09:00:00Z", "2026-02-01T08:00:00Z"],
      empty: {},
      emptyList: [],
      nil: null,
      truthy: true,
      count: 42,
      negative: -17,
    },
    governance: { purpose: "coordination:proposal", ttlSeconds: 1209600 },
  },
});

addObjectVector({
  id: "003-expiry-boundary-not-yet-expired",
  description:
    "Expires one second after `now`. MUST be accepted. Guards against an off-by-one that rejects still-valid objects.",
  requires: ["governance", "processing"],
  expect: "accept",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({
    id: "01948f00-0000-7000-8000-000000000003",
    issuedAt: NOW,
    governance: { purpose: "comms:message", expiresAt: "2026-01-15T12:00:01.000Z" },
  }),
});

addObjectVector({
  id: "004-no-expiry-declared",
  description:
    "Neither ttlSeconds nor expiresAt. Does not expire; a receiver MAY apply a local maximum lifetime but MUST NOT reject solely for the absence of an expiry.",
  requires: ["governance"],
  expect: "accept",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({
    id: "01948f00-0000-7000-8000-000000000004",
    governance: { purpose: "comms:message" },
  }),
});

/* --- reject: signature --- */

addObjectVector({
  id: "010-tampered-payload",
  description: "Payload altered after signing.",
  requires: ["governed-object"],
  expect: "reject",
  reason: "signature-invalid",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000010" }),
  mutate: (o) => ({ ...o, payload: { text: "goodbye" } }),
});

addObjectVector({
  id: "011-tampered-purpose",
  description:
    "Declared purpose altered after signing. Proves the governance block is inside the signature: a relay cannot broaden the purpose under which data was disclosed.",
  requires: ["canonical", "governance"],
  expect: "reject",
  reason: "signature-invalid",
  permittedPurposes: ["comms:message", "commerce:intent"],
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000011" }),
  mutate: (o) => ({ ...o, governance: { ...o.governance, purpose: "commerce:intent" } }),
});

addObjectVector({
  id: "012-tampered-expiry-extended",
  description:
    "Expiry extended after signing. Proves retention limits cannot be silently lengthened by a receiver or relay.",
  requires: ["canonical", "governance"],
  expect: "reject",
  reason: "signature-invalid",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000012" }),
  mutate: (o) => ({ ...o, governance: { ...o.governance, ttlSeconds: 315360000 } }),
});

addObjectVector({
  id: "013-issuer-key-mismatch",
  description:
    "Validly signed by Bob's key but claims Alice as issuer. The signature is well-formed; it is simply not Alice's. A verifier that checks signature validity without binding it to issuerDid will wrongly accept.",
  requires: ["identity", "governed-object"],
  expect: "reject",
  reason: "signature-not-by-issuer",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000013", issuerDid: ALICE_DID }),
  key: BOB.privateKey,
});

addObjectVector({
  id: "014-signature-not-base64",
  description: "Signature member is not valid base64.",
  requires: ["governed-object"],
  expect: "reject",
  reason: "malformed",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000014" }),
  mutate: (o) => ({ ...o, signature: "not!valid!base64!" }),
});

/* --- reject: expiry --- */

addObjectVector({
  id: "020-expired-by-ttl",
  description: "issuedAt + ttlSeconds is before `now`.",
  requires: ["governance", "processing"],
  expect: "reject",
  reason: "expired",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({
    id: "01948f00-0000-7000-8000-000000000020",
    issuedAt: "2026-01-15T10:00:00.000Z",
    governance: { purpose: "comms:message", ttlSeconds: 60 },
  }),
});

addObjectVector({
  id: "021-expired-by-absolute",
  description: "expiresAt is before `now`.",
  requires: ["governance", "processing"],
  expect: "reject",
  reason: "expired",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({
    id: "01948f00-0000-7000-8000-000000000021",
    governance: { purpose: "comms:message", expiresAt: "2026-01-15T11:00:00.000Z" },
  }),
});

addObjectVector({
  id: "022-expiry-earlier-of-both-wins",
  description:
    "ttlSeconds implies an expiry far in the future, expiresAt is in the past. The earlier instant governs, so this MUST be rejected. An implementation that only reads whichever field it finds first will wrongly accept.",
  requires: ["governance"],
  expect: "reject",
  reason: "expired",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({
    id: "01948f00-0000-7000-8000-000000000022",
    issuedAt: "2026-01-15T11:00:00.000Z",
    governance: {
      purpose: "comms:message",
      ttlSeconds: 31536000,
      expiresAt: "2026-01-15T11:30:00.000Z",
    },
  }),
});

addObjectVector({
  id: "023-expiry-earlier-of-both-wins-ttl",
  description:
    "The mirror of 022, and the case that actually catches the common bug. ttlSeconds implies an expiry in the past while expiresAt is far in the future. The earlier instant governs, so this MUST be rejected. An implementation that checks expiresAt first and returns early will wrongly accept, silently extending a short-lived object's lifetime by years.",
  requires: ["governance"],
  expect: "reject",
  reason: "expired",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({
    id: "01948f00-0000-7000-8000-000000000023",
    issuedAt: "2026-01-15T11:00:00.000Z",
    governance: {
      purpose: "comms:message",
      ttlSeconds: 60,
      expiresAt: "2027-01-15T11:30:00.000Z",
    },
  }),
});

/* --- reject: purpose --- */

addObjectVector({
  id: "030-purpose-not-permitted",
  description:
    "Well-formed and unexpired, but the declared purpose is outside the receiver's permitted set for this context. MUST be rejected; the permitted set is the receiver's configuration and is never derived from the object.",
  requires: ["purpose-enforcement"],
  expect: "reject",
  reason: "purpose-not-permitted",
  permittedPurposes: ["comms:message", "comms:receipt"],
  unsigned: base({
    id: "01948f00-0000-7000-8000-000000000030",
    semantic: { schema: "https://atom.qwixl.dev/schema/ActionCapture" },
    payload: { amountPence: 500000 },
    governance: { purpose: "action:capture", ttlSeconds: 3600 },
  }),
});

/* --- reject: structural --- */

addObjectVector({
  id: "040-unsupported-version",
  description: "version is not 1.",
  requires: ["governed-object"],
  expect: "reject",
  reason: "malformed",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000040" }),
  mutate: (o) => ({ ...o, version: 2 }),
});

addObjectVector({
  id: "041-unsupported-signature-algorithm",
  description:
    "signatureAlgorithm is not ed25519. MUST be rejected rather than the algorithm being inferred from the key or the signature length.",
  requires: ["governed-object"],
  expect: "reject",
  reason: "malformed",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000041" }),
  mutate: (o) => ({ ...o, signatureAlgorithm: "secp256k1" }),
});

addObjectVector({
  id: "042-missing-purpose",
  description: "governance.purpose absent. Purpose is mandatory.",
  requires: ["governance"],
  expect: "reject",
  reason: "malformed",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000042" }),
  mutate: (o) => {
    const governance = { ...o.governance };
    delete governance.purpose;
    return { ...o, governance };
  },
});

addObjectVector({
  id: "043-issuer-not-did-key",
  description: "issuerDid is not a did:key identifier.",
  requires: ["identity"],
  expect: "reject",
  reason: "malformed",
  permittedPurposes: DEFAULT_PERMITTED,
  unsigned: base({ id: "01948f00-0000-7000-8000-000000000043" }),
  mutate: (o) => ({ ...o, issuerDid: "did:web:example.com" }),
});

/* --- replay --- */

{
  const first = sign(
    base({ id: "01948f00-0000-7000-8000-000000000050", governance: { purpose: "action:capture", ttlSeconds: 3600 } }),
    ALICE.privateKey,
  );
  vectors.push({
    id: "050-replay-same-id",
    kind: "data-object-sequence",
    description:
      "The identical object is presented twice. The first MUST be accepted and the second MUST be rejected. Where an object conveys an instruction with side effects — a capture, a booking, a consent grant — replay is directly exploitable, and a valid signature is no defence because the object genuinely was signed by its issuer.",
    requires: ["replay"],
    now: NOW,
    permittedPurposes: ["action:capture"],
    sequence: [
      { expect: "accept", object: first.object },
      { expect: "reject", reason: "replay", object: structuredClone(first.object) },
    ],
  });

  const differentId = sign(
    base({ id: "01948f00-0000-7000-8000-000000000051", governance: { purpose: "action:capture", ttlSeconds: 3600 } }),
    ALICE.privateKey,
  );
  vectors.push({
    id: "051-distinct-ids-not-replay",
    kind: "data-object-sequence",
    description:
      "Two objects with identical content but distinct ids. Both MUST be accepted. Guards against replay protection implemented by hashing the payload, which would wrongly reject a legitimate repeat instruction.",
    requires: ["replay"],
    now: NOW,
    permittedPurposes: ["action:capture"],
    sequence: [
      { expect: "accept", object: first.object },
      { expect: "accept", object: differentId.object },
    ],
  });
}

/* --- credential binding --- */

vectors.push({
  id: "060-credential-binding-mismatch",
  kind: "credential-binding",
  description:
    "An MLS KeyPackage whose basic-credential identity asserts Alice's DID while its LeafNode signature key is Bob's. MUST be rejected and the member MUST NOT be added to a group. Without this check the DID in a credential is an unverified claim, and any party may publish a KeyPackage asserting another agent's identity.",
  requires: ["credential-binding"],
  expect: "reject",
  reason: "credential-key-mismatch",
  credentialIdentity: ALICE_DID,
  leafSignatureKey: BOB.publicKey.toString("base64"),
});

vectors.push({
  id: "061-credential-binding-match",
  kind: "credential-binding",
  description:
    "Credential identity and LeafNode signature key are the same Ed25519 key. MUST be accepted.",
  requires: ["credential-binding"],
  expect: "accept",
  credentialIdentity: ALICE_DID,
  leafSignatureKey: ALICE.publicKey.toString("base64"),
});

/* --- encapsulation (A2A v1.0 part serialisation) --- */

/*
 * These vectors are the JSON a peer actually transmits, not any implementation's
 * internal representation of it. An implementation generated from the A2A
 * protocol buffer schema presents part content as a tagged union, and describing
 * that form as though it were the wire format is precisely the mistake the
 * encapsulation section of -01 exists to prevent: it is invisible to a single
 * implementation, which both writes and reads its own internal shape, and only
 * surfaces when a second implementation in another language tries to interoperate
 * from the description.
 *
 * `readAs` is the media type the receiver is looking for. Acceptance means the
 * receiver resolved this part to that media type and can hand the `data` member
 * to the layer above.
 */

const DATA_OBJECT_MEDIA_TYPE = "application/vnd.atom.data-object+json;version=1";
const MLS_WIRE_MEDIA_TYPE = "application/vnd.atom.mls-wire+cbor;version=1";
const MLS_HANDSHAKE_MEDIA_TYPE = "application/vnd.atom.mls-handshake+json;version=1";

const ENCAPSULATED_OBJECT = sign(
  base({
    id: "01948f00-0000-7000-8000-000000000070",
    governance: { purpose: "comms:message", ttlSeconds: 3600 },
  }),
  ALICE.privateKey,
).object;

function addPartVector({ id, description, expect, reason, readAs, part }) {
  vectors.push({
    id,
    kind: "encapsulation-part",
    description,
    requires: ["encapsulation", "media-type-placement"],
    expect,
    ...(reason ? { reason } : {}),
    readAs,
    part,
  });
}

addPartVector({
  id: "070-part-media-type-both-positions",
  description:
    "The form a conforming sender produces: the media type in the part's own mediaType member and in the data member, identical. MUST be accepted.",
  expect: "accept",
  readAs: DATA_OBJECT_MEDIA_TYPE,
  part: {
    data: { mediaType: DATA_OBJECT_MEDIA_TYPE, object: ENCAPSULATED_OBJECT },
    mediaType: DATA_OBJECT_MEDIA_TYPE,
  },
});

addPartVector({
  id: "071-part-media-type-part-member-only",
  description:
    "Media type declared only in the part member, as a generic A2A v1.0 tool with no knowledge of this specification's envelope would produce. MUST be accepted.",
  expect: "accept",
  readAs: DATA_OBJECT_MEDIA_TYPE,
  part: {
    data: { object: ENCAPSULATED_OBJECT },
    mediaType: DATA_OBJECT_MEDIA_TYPE,
  },
});

addPartVector({
  id: "072-part-media-type-data-member-only",
  description:
    "Media type declared only inside the data member, as a peer speaking A2A v0.3 produces — that version had no mediaType member on a part. MUST be accepted, and this is the requirement that keeps an incrementally upgraded network working.",
  expect: "accept",
  readAs: DATA_OBJECT_MEDIA_TYPE,
  part: {
    data: { mediaType: DATA_OBJECT_MEDIA_TYPE, object: ENCAPSULATED_OBJECT },
  },
});

addPartVector({
  id: "073-part-media-type-conflict",
  description:
    "The two media type declarations disagree. MUST be rejected. A receiver that trusts one member and ignores the other processes this part as a different message from a receiver that trusts the other, so accepting it makes the meaning of a message depend on which member the receiver happens to read. Where the two implementations sit on the same network, a sender chooses which of them acts.",
  expect: "reject",
  reason: "media-type-conflict",
  readAs: DATA_OBJECT_MEDIA_TYPE,
  part: {
    data: { mediaType: MLS_WIRE_MEDIA_TYPE, object: ENCAPSULATED_OBJECT },
    mediaType: DATA_OBJECT_MEDIA_TYPE,
  },
});

addPartVector({
  id: "074-part-media-type-absent",
  description:
    "No media type in either position. MUST be rejected rather than inferred from the shape of the data member, which would let a sender have a payload interpreted under a media type it never declared.",
  expect: "reject",
  reason: "malformed",
  readAs: DATA_OBJECT_MEDIA_TYPE,
  part: {
    data: { object: ENCAPSULATED_OBJECT },
  },
});

addPartVector({
  id: "075-part-content-not-data",
  description:
    "A text part whose mediaType claims this specification's media type. MUST be rejected: the encodings require the content to be a data part, and a receiver that parses text content as an envelope accepts payloads the specification does not admit.",
  expect: "reject",
  reason: "malformed",
  readAs: DATA_OBJECT_MEDIA_TYPE,
  part: {
    text: JSON.stringify({ mediaType: DATA_OBJECT_MEDIA_TYPE, object: ENCAPSULATED_OBJECT }),
    mediaType: DATA_OBJECT_MEDIA_TYPE,
  },
});

addPartVector({
  id: "076-part-media-type-not-the-one-sought",
  description:
    "A well-formed MLS wire part offered to a receiver looking for a Governed Object part. MUST be rejected. Guards against a receiver that dispatches on the shape of the data member and treats the media type as decoration.",
  expect: "reject",
  reason: "media-type-not-matched",
  readAs: DATA_OBJECT_MEDIA_TYPE,
  part: {
    data: { mediaType: MLS_WIRE_MEDIA_TYPE, wire: "AAECAwQFBgcICQoLDA0ODw==" },
    mediaType: MLS_WIRE_MEDIA_TYPE,
  },
});

addPartVector({
  id: "077-mls-wire-part",
  description: "An MLS wire part in the form a conforming sender produces. MUST be accepted.",
  expect: "accept",
  readAs: MLS_WIRE_MEDIA_TYPE,
  part: {
    data: { mediaType: MLS_WIRE_MEDIA_TYPE, wire: "AAECAwQFBgcICQoLDA0ODw==" },
    mediaType: MLS_WIRE_MEDIA_TYPE,
  },
});

addPartVector({
  id: "078-mls-handshake-part",
  description: "An MLS handshake part in the form a conforming sender produces. MUST be accepted.",
  expect: "accept",
  readAs: MLS_HANDSHAKE_MEDIA_TYPE,
  part: {
    data: {
      mediaType: MLS_HANDSHAKE_MEDIA_TYPE,
      initiatorDid: ALICE_DID,
      welcome: "AAECAwQFBgcICQoLDA0ODw==",
      ratchetTree: "EBESExQVFhcYGRobHB0eHw==",
    },
    mediaType: MLS_HANDSHAKE_MEDIA_TYPE,
  },
});

/* -------------------------------------------------------------------- emit --- */

mkdirSync(OUT_DIR, { recursive: true });

for (const vector of vectors) {
  writeFileSync(join(OUT_DIR, `${vector.id}.json`), `${JSON.stringify(vector, null, 2)}\n`, "utf8");
}

const manifest = {
  specification: "draft-chapman-a2a-mls-00",
  generated: "deterministic — regenerate with `node spec/vectors/generate.mjs`",
  identities: {
    alice: { did: ALICE_DID, publicKeyBase64: ALICE.publicKey.toString("base64") },
    bob: { did: BOB_DID, publicKeyBase64: BOB.publicKey.toString("base64") },
  },
  evaluationInstant: NOW,
  counts: {
    total: vectors.length,
    accept: vectors.filter((v) => v.expect === "accept").length,
    reject: vectors.filter((v) => v.expect === "reject").length,
    sequences: vectors.filter((v) => v.kind === "data-object-sequence").length,
    encapsulation: vectors.filter((v) => v.kind === "encapsulation-part").length,
  },
  vectors: vectors.map((v) => ({
    id: v.id,
    kind: v.kind,
    requires: v.requires,
    ...(v.expect ? { expect: v.expect } : {}),
    ...(v.reason ? { reason: v.reason } : {}),
  })),
};
writeFileSync(join(OUT_DIR, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

console.log(`wrote ${vectors.length} vectors + manifest.json to ${OUT_DIR}`);
console.log(`  alice ${ALICE_DID}`);
console.log(`  bob   ${BOB_DID}`);
